name = "TelegramClient"
uuid = "0c50e747-7910-4d75-be1d-ae33d9528add"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.3.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TDLib_jll = "6cfef11d-eb86-5696-bb50-1df673c3ffa1"

[compat]
JSON3 = "1.8"
StructTypes = "1.7"
TDLib_jll = "1.7"
julia = "1.6"
