name = "TelegramClient"
uuid = "0c50e747-7910-4d75-be1d-ae33d9528add"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.2.0-dev"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
TDLib_jll = "6cfef11d-eb86-5696-bb50-1df673c3ffa1"

[compat]
JSON3 = "1.8"
Setfield = "0.7"
TDLib_jll = "1.6"
julia = "1.6"
